### ISSUE TITLE
Blue apple

### ISSUE THREAD

**Issue by LucaBarbaLata** [LucaBarbaLata/Fuzzy#5]
That gives you speed for 2 min

**Comment by LucaBarbaLata** [comment]
Craftin recipe for the blue apple.

A normal apple with lapis on its sides

**Comment by DenisGithubWabibi** [comment]
@LucaBarbaLata sa adaugi efectul de speed

**Comment by DenisGithubWabibi** [comment]
added in 46c0672
crafted by surronding an apple with 8 blue dye

**Comment by LucaBarbaLata** [comment]
Todo:

Add speed effect - @LucaBarbaLata

**Comment by LucaBarbaLata** [comment]
Added in d268108
